# Panic due to api body size. 

**bpastiu** commented *Mar 4, 2020*

Hello,

We've encountered an interesting issue while deploying one of our stacks.
I can't go into specifics of the configuration for obvious reasons but I'll try to explain the best I can.

We are trying to deploy a aws_api_gateway_rest_api resource with the body being a rendered openapi template file.
We didn't experience any issues up until now when there were some changes done to the openapi file.
The openapi file is now about 3500 lines big and is causing the panic. We tested that this is the issue using a smaller openapi file and it worked fine.

I would like to as if there is any limitation to this we should take into account going forward and how we could get it resolved.

Added a TF_LOG=trace to extract some logs. It happens here when it tries to create the tf state file for this module in s3. Every module has it's own tfstate file.
In the respective bucket the api-gateway key is missing in entirety.

[terragrunt] [/config/account/region/environment/api-gateway] 2020/03/04 16:30:12 Running command: terraform init -backend-config=bucket=bucket-name -backend-config=dynamodb_table=dynamo-db-table -backend-config=encrypt=true -backend-config=key=12345/environment/api-gateway/terraform.tfstate -backend-config=region=region

Here is the panig message:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd37d71]

goroutine 53 [running]:
github.com/gruntwork-io/terragrunt/cli.runTerraformWithRetry(0xc0000db600, 0xc0000db600, 0xc0002f8900)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:531 +0x121
github.com/gruntwork-io/terragrunt/cli.runTerragruntWithConfig.func1(0x0, 0x0)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:484 +0x2a
github.com/gruntwork-io/terragrunt/cli.runActionWithHooks(0xf9a250, 0x9, 0xc0000db600, 0xc0002a8140, 0xc00043bc20, 0xc0004ee500, 0xc00060a140)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:495 +0x2ae
github.com/gruntwork-io/terragrunt/cli.runTerragruntWithConfig(0xc0000db600, 0xc0002a8140, 0x0, 0x0, 0x0)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:483 +0x2c7
github.com/gruntwork-io/terragrunt/cli.RunTerragrunt(0xc0000db600, 0xfa49a3, 0x15)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:370 +0x79c
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runNow(0xc0005c7c20, 0x0, 0x0)
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:238 +0x17a
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runModuleWhenReady(0xc0005c7c20)
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:201 +0x6a
github.com/gruntwork-io/terragrunt/configstack.runModules.func1(0xc00009f150, 0xc0005c7c20)
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:171 +0x51
created by github.com/gruntwork-io/terragrunt/configstack.runModules
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:169 +0xe1
Makefile:68: recipe for target 'apply' failed
make: *** [apply] Error 2

I had a issue opened on terraform github and was redirected here. 
This is the issue:
https://github.com/hashicorp/terraform/issues/24240
<br />
***


**yorinasub17** commented *Mar 4, 2020*

Apologies for the ping ponging here since I was the original one to kick you over to terraform. The stack trace helps a lot in clarifying what is going on here.

I still think this is a terraform error under the hood, but the terraform error is being masked by a different terragrunt bug, which is poor error handling in the retry logic. I'll be investigating if there is a easy fix for that.

In the meantime, can you rerun your config with just terraform, no terragrunt and see if you can see the underlying error? You can do this by using a tfvars file instead of terragrunt.


***

**bpastiu** commented *Mar 4, 2020*

Hi. 

Thanks for the reply.

I will try and do that tomorrow at the office and come back here.
***

**yorinasub17** commented *Mar 13, 2020*

Not sure if you had a chance to test this, but I have fixed the source of panic in terragrunt. If you use `v0.23.1`, you should now see the underlying terraform error as opposed to the terragrunt panic even going through terragrunt.
***

