# terragrunt not creating the s3 bucket

**madhuryg** commented *Sep 24, 2020*

terraform version 0.13.3
terragrunt version v0.23.40
Not creating the s3 bucket by default if not found..
[terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12] 2020/09/24 00:31:51 Initializing remote state for the s3 backend
[terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12] 2020/09/24 00:31:51 [terragrunt] [C:\Users\Madhuri.Gattupalli\projects\aurora\AWSDevOps\Terragrunt\qa\postgres-parameter-group-12]  Remote state S3 bucket inovalon.qsixl.analytics.terraform-backend.qa does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)

[terragrunt] 2020/09/24 00:31:51
[terragrunt] 2020/09/24 00:31:51 Encountered the following errors:
NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 3D6539020EF9EE1F, host id: kNaqX/XiD7t+MpD+jydwxnwtDoI6vyCixuf3LSJoJYWSfYUhF14DquP0ZBW3KHN1FjsJpr9uBLY=
Cannot process module Module C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-rds-aurora2 (excluded: false, dependencies: [C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-parameter-group-12]) because one of its dependencies, Module C:/Users/Madhuri.Gattupalli/projects/aurora/AWSDevOps/Terragrunt/qa/postgres-parameter-group-12 (excluded: false, dependencies: []), finished with an error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 3D6539020EF9EE1F, host id: kNaqX/XiD7t+MpD+jydwxnwtDoI6vyCixuf3LSJoJYWSfYUhF14DquP0ZBW3KHN1FjsJpr9uBLY=
[terragrunt] 2020/09/24 00:31:51 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

<br />
***


**brikis98** commented *Sep 25, 2020*

Did you enter `y`? 

Is it possible the bucket exists already in some AWS account, but you're authenticated to a different account?
***

**ChristophShyper** commented *Sep 28, 2020*


> Is it possible the bucket exists already in some AWS account, but you're authenticated to a different account?

Exactly. This error is typically caused by wrong credentials.

Also use Terragrunt 0.25 for Terraform 0.13.

***

**madhuryg** commented *Sep 28, 2020*

thank u ... s3 was not existing .... let me upgrade the version

On Mon, Sep 28, 2020 at 5:22 AM Krzysztof Szyper <notifications@github.com>
wrote:

> Is it possible the bucket exists already in some AWS account, but you're
> authenticated to a different account?
>
> Exactly. This error is typically caused by wrong credentials.
>
> Also use Terragrunt 0.25 for Terraform 0.13.
>
> â€”
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gruntwork-io/terragrunt/issues/1370#issuecomment-699889707>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADVMQE7WZ5OFFVSXZ5OQ23TSIBIWJANCNFSM4RX2DAGQ>
> .
>

***

**brikis98** commented *Jan 18, 2021*

Sounds like a creds or usage error, and no follow up in a few months, so closing.
***

