# Permision Denied S3 with admin user

**DMEvanCT** commented *Jan 3, 2021*

Here is the terragrunt hcl.  This was for a demo so I am not worried about data

# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "terraform-state-dev"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
    bucket         = "terraform-dmitdemo-dev"
  }
}

Here is the error I get. 

1.) The user is an admin though so I am not sure how it is denied. 
2.) Terragrunt created the S3 bucket to begin with. 

Error refreshing state: AccessDenied: Access Denied
        status code: 403, request id: 54448C00919BBEB4, host id: xXpmDCZDk/GmqQhoyraaQdLIBO1377BmYuV76+2XQ1nt5cBMhz7mWlWtZhhd4pja1KJaacswZBs=
[terragrunt] 2021/01/02 23:15:43 Hit multiple errors:


<br />
***


**yorinasub17** commented *Jan 4, 2021*

This is a bit hard to debug without seeing the terragrunt config (what you have in `terragrunt.hcl`, `remote_state` block), but one thing to sanity check is your account config to make sure the bucket is in the right account. A common issue we've seen is that the auth parameters when running `terragrunt` for the first time was misconfigured and created the bucket in the wrong target account from where you intended.
***

**fliphess** commented *Feb 3, 2021*

I'm having the same issue after upgrading terragrunt from `0.23.38` to `0.27.3`: The bucket is in the same flat account as before and was created by the same "terraform" user having the admin role (we don't use organisations in this account, terraform get's it's api credentials from the environment) 

My remote_state block is: 
```
remote_state {
  backend = "s3"
  config = {
    bucket         = "some-name-tfstate"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "eu-central-1"
    encrypt        = true
    dynamodb_table = "terraform-some-name-tflock"

    skip_metadata_api_check     = true
    skip_region_validation            = true
    skip_credentials_validation.   = true
  }
}
```
***

**fliphess** commented *Feb 4, 2021*

Found my issue which was not related to terragrunt: some idiot (me) disabled the wrong api credentials....

***

**yorinasub17** commented *Sep 27, 2021*

Closing this as stale. If this is still an issue, please open a new ticket with updated context requested in https://github.com/gruntwork-io/terragrunt/issues/1477#issuecomment-754179156. Thanks!
***

