# The given plan file can no longer be applied because the state was changed

**dkirrane** commented *Oct 25, 2022*

I have `retryable_errors` configured. However, on retry it fails with state was changed.
The plan in question is creating 3 different vms with `vsphere_virtual_machine` resource.
I'm running terragrunt in docker `alpine/terragrunt:1.3.3`

```hcl
retryable_errors = [
  "(?s).*error cloning virtual machine: Could not complete network copy for file.*"
]

retry_max_attempts = 3
retry_sleep_interval_sec = 30
```

```
Error: error cloning virtual machine: Could not complete network copy for file /vmfs/volumes/5c52abc7-db3xyz34-98e7-b0262823da3a/ubuntu/ubuntu.vmdk

  with vsphere_virtual_machine.this,
  on main.tf line 42, in resource "vsphere_virtual_machine" "this":
  42: resource "vsphere_virtual_machine" "this" {

Releasing state lock. This may take a few moments...
time=2022-10-25T13:38:36Z level=info msg=Encountered an error eligible for retrying. Sleeping 30s before retrying.

Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: Saved plan is stale

The given plan file can no longer be applied because the state was changed by
another operation after the plan was created.
```
<br />
***


