# mock_outputs is not working for depended modules with run-all plan

**tomerleib** commented *Jan 5, 2023*

Hi, 
I'm trying to configure a relatively simple case of having two modules where one depends on the other.  
I am using the instructions from here: https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency:  
```hcl
dependency "vpc" {
  config_path = "../vpc"

  mock_outputs = {
    mock_outputs_allowed_terraform_commands = ["plan"]
    vpc_id = "vpc-00000000"
    private_subnets = [
      "subnet-00000000",
      "subnet-00000001",
      "subnet-00000002",
    ]
  }
}



inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
  private_subnets = dependency.vpc.outputs.private_subnets
}
```

But when I am trying to execute the `terragrunt run-all plan` or any other `run-all` commands, I'm getting errors:
`Unsupported attribute; This object does not have an attribute named "private_subnets"`
`Unsupported attribute; This object does not have an attribute named "vpc_id"`

Of course, if I go ahead and create the VPC, I will not get those errors; however, that is where `mock_outputs` should work to provide the outputs if there are none.
What am I missing here?

`Terragrunt v0.39.2`

<br />
***


**denis256** commented *Jan 6, 2023*

Hi,
I tried to reproduce a similar case but it is not generating any error during the execution of `terragrunt run-all plan`

https://github.com/denis256/terragrunt-tests/tree/master/issue-2405
***

**tomerleib** commented *Jan 8, 2023*

It seems to happen sporadically here.
After I removed the cache and deleted the statefile, it worked as expected.
I've made some changes in the code and changed something in the `vpc` module, and it stopped working again.
***

**jclangst** commented *May 10, 2023*

This occurred to us when the following steps occurred:

1. Ran `terragrunt run-all init` with dependencies but without `mock_outputs`; this run failed
2. Added `mock_outputs`
3. Ran `terragrunt run-all init` and ran into this error

Was only able to resolve by destroying to clear cache and state file.

Present in `v0.42.8`
***

**jclangst** commented *May 31, 2023*

Also ended up in this bug state whenever a new module is added and the first subsequent `run-all init` fails.
***

