# Terraform can't find remote S3 backend after creation

**jamie3** commented *Aug 12, 2019*

I have two AWS accounts each with their own S3 remote backend storage. 

~/.aws/credentials
```
[default]
aws_access_key_id=...
aws_secret_access_key=...

[development]
aws_access_key_id=...
aws_secret_access_key=...

[production]
aws_access_key_id=...
aws_secret_access_key=...
```

My terraform/terragrunt folder structure is as follows.

```
infrastructure\ec2\main.tf
live\development\terragrunt.hcl
live\development\ec2\terragrunt.hcl
live\production\terragrunt.hcl
live\production\ec2\terragrunt.hcl
```

live\production\terragrunt.hcl
```hcl
remote_state {
  backend = "s3"
  config = {
    bucket         = "my-terraform-production"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-west-2"
    encrypt        = true
    #dynamodb_table = "my-lock-table"
    profile = "production"
    dynamodb_table = "production-terraform-lock-table"
  }
}

inputs = {
  aws_profile = "production"
  domain_name = "my-domain-name.com"

  region = "us-west-2"
}
```

Apply terragrunt. This creates the S3 remote backend in the proper account, but then when terraform tries to connect to the S3 bucket it gets a 404.

```
cd live\production\ec2
terragrunt apply

[terragrunt] [C:\dev\code\terraform\live\production\ec2] 2019/08/12 09:51:47 Running command: terraform init -backend-config=key=production/ec2/terraform.tfstate -backend-config=profile=production -backend-config=region=us-west-2 -backend-config=bucket=my-terraform-production --backend-config=dynamodb_table=production-terraform-lock-table -backend-config=encrypt=true

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Error: Error inspecting states in the "s3" backend:
    S3 bucket does not exist.

The referenced S3 bucket must have been previously created. If the S3 bucket
was created within the last minute, please wait for a minute or two and try
again.

Error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 478AD5AD94478808, host id: xxxxxx=


Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the
destination remain unmodified. Please resolve the above error and try again.
```

I've waited several minutes and still get the same error.


<br />
***


**jamie3** commented *Aug 12, 2019*

Enabling TF_LOG=DEBUG revealed that the call to S3 is using the wrong account. The account id should end with 44 not 33.

```xml
<GetCallerIdentityResult>
    <Arn>arn:aws:iam::XXXXXXX33:user/jamie</Arn>
    <UserId>AAA</UserId>
    <Account>XXXXXXXX33</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>4a7df9b6-bd1a-11e9-8138-3f106a5b6768</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
```
***

**brikis98** commented *Aug 13, 2019*

Is your `production` profile pointing to the right account? Do you have any other creds set in your environment?
***

**jamie3** commented *Aug 13, 2019*

No other creds set. Here is my ~/.aws/config

```
[default]
region=us-west-2
output=json

[profile production]
role_arn=arn:aws:iam::XXXXXXXX44:role/jamie
```
***

**jamie3** commented *Aug 13, 2019*

It seems to use the proper account on the first `<GetCallerIdentityResult>` but second it uses the wrong account.

```
-----------------------------------------------------
2019/08/13 11:35:50 [DEBUG] [aws-sdk-go] DEBUG: Response sts/GetCallerIdentity Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 402
Content-Type: text/xml
Date: Tue, 13 Aug 2019 17:35:49 GMT
X-Amzn-Requestid: XXX


-----------------------------------------------------
2019/08/13 11:35:50 [DEBUG] [aws-sdk-go] <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:iam::XXXXXXXX44:user/jamie</Arn>
    <UserId>XXX</UserId>
    <Account>XXXXXXXX44</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>cab34e12-bdf0-11e9-9ade-f9201dcf114b</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
2019/08/13 11:35:50 [INFO] Setting AWS metadata API timeout to 100ms
2019/08/13 11:35:50 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2019/08/13 11:35:50 [INFO] AWS Auth provider used: "SharedCredentialsProvider"
2019/08/13 11:35:50 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2019/08/13 11:35:50 [DEBUG] [aws-sdk-go] DEBUG: Request sts/GetCallerIdentity Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: sts.amazonaws.com
User-Agent: aws-sdk-go/1.20.19 (go1.12.4; windows; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.5
Content-Length: 43
Authorization: XXX
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20190813T173550Z
Accept-Encoding: gzip

Action=GetCallerIdentity&Version=2011-06-15
-----------------------------------------------------
2019/08/13 11:35:51 [DEBUG] [aws-sdk-go] DEBUG: Response sts/GetCallerIdentity Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 402
Content-Type: text/xml
Date: Tue, 13 Aug 2019 17:35:50 GMT
X-Amzn-Requestid: cb16a448-bdf0-11e9-9276-0d986dbe79cf


-----------------------------------------------------
2019/08/13 11:35:51 [DEBUG] [aws-sdk-go] <GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <GetCallerIdentityResult>
    <Arn>arn:aws:iam::XXXXXXXX33:user/jamie</Arn>
    <UserId>XXX</UserId>
    <Account>XXXXXXXX33</Account>
  </GetCallerIdentityResult>
  <ResponseMetadata>
    <RequestId>cb16a448-bdf0-11e9-9276-0d986dbe79cf</RequestId>
  </ResponseMetadata>
</GetCallerIdentityResponse>
2019/08/13 11:35:51 [DEBUG] [aws-sdk-go] DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /?prefix=env%3A%2F HTTP/1.1
Host: neo-production-terraform.s3.us-west-2.amazonaws.com
User-Agent: aws-sdk-go/1.20.19 (go1.12.4; windows; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.5
Authorization: XXX
X-Amz-Content-Sha256: XXX
X-Amz-Date: 20190813T173551Z
Accept-Encoding: gzip


-----------------------------------------------------
2019/08/13 11:35:51 [DEBUG] [aws-sdk-go] DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 13 Aug 2019 17:35:50 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-west-2
X-Amz-Id-2: XXX
X-Amz-Request-Id: XXX
```
***

**jamie3** commented *Aug 13, 2019*

Once I set `export AWS_PROFILE=production` it was able to connect to the s3 bucket.
***

**jamie3** commented *Aug 13, 2019*

It would be ideal if I didnt have to set the `AWS_PROFILE`
***

**BrettFagerlund** commented *Aug 28, 2019*

I've also seen issues around this.

Moved to using --terragrunt-iam-role flag instead of defining the profile in the backend config as it will always pull back the ID from that role rather than default profile. It's removed a lot of repetition around the provider and backend definitions too.

***

**michelzanini** commented *Sep 20, 2020*

I have faced this issue as well.

Here's my backend config:

```
terraform {
  backend "s3" {
    key            = "test/sandbox/test/terraform.tfstate"
    profile        = "sandbox"
    region         = "eu-west-1"
    bucket         = "tdl-test-terragrunt"
    dynamodb_table = "terraform-lock-table"
    encrypt        = true
  }
}

```

I use `profile` on `remote_state` and it fails to create the S3 bucket properly with:

```
[terragrunt] 2020/09/20 13:31:17 Create S3 bucket tdl-test-terragrunt returned an error: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: a55b35ac-9204-4074-a127-07fd95f012b9. Sleeping for 10s and will try again.
```

It worked if I set `AWS_PROFILE` environment variable to `sandbox`, but it should need to have this variable defined to work.

I wonder if this is not something simple to fix? On the S3 bucket logic to consider the `profile` from `remote_state` ?



***

**ericrini** commented *Nov 22, 2020*

```
The referenced S3 bucket must have been previously created. If the S3 bucket
was created within the last minute, please wait for a minute or two and try
again.

Error: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: 478AD5AD94478808, host id: xxxxxx=
```

This error can happen if you initialize terraform successfully, and then delete the bucket that it initialized into. 

When you try to initialize it again with a new bucket name it will give this exact same error. It's confusing because you assume that it's talking about the new bucket not existing since there's no bucket name in the error message.

One possible "fix" is to rename (or delete) the .terraform folder.
***

**yorinasub17** commented *Sep 27, 2021*

In addition to the comment above, I believe this is more stable now if you use the generate pattern of `remote_state` (see [generate attr of remote_state docs](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state)). The `generate` pattern will properly propagate the `profile` field which should sync the way terragrunt and terraform authenticates.

If this is still an issue, please open a new issue with an updated example using the `generate` attr on `remote_state`. Thanks!
***

